# Example seeding file
#
# # Each line referes to the model object to be created and the file that contains the data
#
# # Make sure that the files are seeded in order by using !omap
--- !omap
# # This will seed Mark items from the file db/seed/data/tr_campaign/marks.csv
 - Mark: tr_campaign/marks
